### ISSUE TITLE
Nuget packager is marked prerelease

### ISSUE THREAD

**Issue by mcintyre321** [tavis-software/Tavis.JsonPointer#1]
Would it be possible to bump the nuget package? It causes any consuming packages to throw errors/warnings. I'm currently trying to publish my fork of your diff code. thanks!

**Comment by darrelmiller** [comment]
At a conference at the moment.  I'll will try and do it in the morning.

Darrel

Sent from my Windows Phone

**Comment by darrelmiller** [comment]
I redeployed as a non-beta package.  Let me know if you have any other issues.

**Comment by mcintyre321** [comment]
Thanks :+1:
